/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_center_com_mylibrary_jni_IotJniUtils */

#ifndef _Included_test_center_com_mylibrary_jni_IotJniUtils
#define _Included_test_center_com_mylibrary_jni_IotJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_center_com_mylibrary_jni_IotJniUtils
 * Method:    getUtlString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_center_com_mylibrary_jni_IotJniUtils_getUrlString
  (JNIEnv *, jclass, jint);

/*
 * Class:     test_center_com_mylibrary_jni_IotJniUtils
 * Method:    getLocalKeys
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_center_com_mylibrary_jni_IotJniUtils_getLocalKeys
  (JNIEnv *, jclass);

/*
 * Class:     test_center_com_mylibrary_jni_IotJniUtils
 * Method:    getAccessSecrey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_center_com_mylibrary_jni_IotJniUtils_getAccessSecrey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
